using UnityEngine;

namespace BP.Utilkit
{
    /// <summary>
    /// A static class containing all 140 web colors.
    /// </summary>
    public static class WebColor
    {
        private static Color ConvertHtmlString(string htmlString)
        {
            if (ColorUtility.TryParseHtmlString(htmlString, out Color color)) return color;
            return Color.magenta;
        }

        public static Color Black => ConvertHtmlString("#000000");
        public static Color Navy => ConvertHtmlString("#000080");
        public static Color DarkBlue => ConvertHtmlString("#00008B");
        public static Color MediumBlue => ConvertHtmlString("#0000CD");
        public static Color Blue => ConvertHtmlString("#0000FF");
        public static Color DarkGreen => ConvertHtmlString("#006400");
        public static Color Green => ConvertHtmlString("#008000");
        public static Color Teal => ConvertHtmlString("#008080");
        public static Color DarkCyan => ConvertHtmlString("#008B8B");
        public static Color DeepSkyBlue => ConvertHtmlString("#00BFFF");
        public static Color DarkTurquoise => ConvertHtmlString("#00CED1");
        public static Color MediumSpringGreen => ConvertHtmlString("#00FA9A");
        public static Color Lime => ConvertHtmlString("#00FF00");
        public static Color SpringGreen => ConvertHtmlString("#00FF7F");
        public static Color Aqua => ConvertHtmlString("#00FFFF");
        public static Color Cyan => ConvertHtmlString("#00FFFF");
        public static Color MidnightBlue => ConvertHtmlString("#191970");
        public static Color DodgerBlue => ConvertHtmlString("#1E90FF");
        public static Color LightSeaGreen => ConvertHtmlString("#20B2AA");
        public static Color ForestGreen => ConvertHtmlString("#228B22");
        public static Color SeaGreen => ConvertHtmlString("#2E8B57");
        public static Color DarkSlateGray => ConvertHtmlString("#2F4F4F");
        public static Color DarkSlateGrey => ConvertHtmlString("#2F4F4F");
        public static Color LimeGreen => ConvertHtmlString("#32CD32");
        public static Color MediumSeaGreen => ConvertHtmlString("#3CB371");
        public static Color Turquoise => ConvertHtmlString("#40E0D0");
        public static Color RoyalBlue => ConvertHtmlString("#4169E1");
        public static Color SteelBlue => ConvertHtmlString("#4682B4");
        public static Color DarkSlateBlue => ConvertHtmlString("#483D8B");
        public static Color MediumTurquoise => ConvertHtmlString("#48D1CC");
        public static Color Indigo => ConvertHtmlString("#4B0082");
        public static Color DarkOliveGreen => ConvertHtmlString("#556B2F");
        public static Color CadetBlue => ConvertHtmlString("#5F9EA0");
        public static Color CornflowerBlue => ConvertHtmlString("#6495ED");
        public static Color RebeccaPurple => ConvertHtmlString("#663399");
        public static Color MediumAquaMarine => ConvertHtmlString("#66CDAA");
        public static Color DimGray => ConvertHtmlString("#696969");
        public static Color DimGrey => ConvertHtmlString("#696969");
        public static Color SlateBlue => ConvertHtmlString("#6A5ACD");
        public static Color OliveDrab => ConvertHtmlString("#6B8E23");
        public static Color SlateGray => ConvertHtmlString("#708090");
        public static Color SlateGrey => ConvertHtmlString("#708090");
        public static Color LightSlateGray => ConvertHtmlString("#778899");
        public static Color LightSlateGrey => ConvertHtmlString("#778899");
        public static Color MediumSlateBlue => ConvertHtmlString("#7B68EE");
        public static Color LawnGreen => ConvertHtmlString("#7CFC00");
        public static Color Chartreuse => ConvertHtmlString("#7FFF00");
        public static Color Aquamarine => ConvertHtmlString("#7FFFD4");
        public static Color Maroon => ConvertHtmlString("#800000");
        public static Color Purple => ConvertHtmlString("#800080");
        public static Color Olive => ConvertHtmlString("#808000");
        public static Color Gray => ConvertHtmlString("#808080");
        public static Color Grey => ConvertHtmlString("#808080");
        public static Color SkyBlue => ConvertHtmlString("#87CEEB");
        public static Color LightSkyBlue => ConvertHtmlString("#87CEFA");
        public static Color BlueViolet => ConvertHtmlString("#8A2BE2");
        public static Color DarkRed => ConvertHtmlString("#8B0000");
        public static Color DarkMagenta => ConvertHtmlString("#8B008B");
        public static Color SaddleBrown => ConvertHtmlString("#8B4513");
        public static Color DarkSeaGreen => ConvertHtmlString("#8FBC8F");
        public static Color LightGreen => ConvertHtmlString("#90EE90");
        public static Color MediumPurple => ConvertHtmlString("#9370DB");
        public static Color DarkViolet => ConvertHtmlString("#9400D3");
        public static Color PaleGreen => ConvertHtmlString("#98FB98");
        public static Color DarkOrchid => ConvertHtmlString("#9932CC");
        public static Color YellowGreen => ConvertHtmlString("#9ACD32");
        public static Color Sienna => ConvertHtmlString("#A0522D");
        public static Color Brown => ConvertHtmlString("#A52A2A");
        public static Color DarkGray => ConvertHtmlString("#A9A9A9");
        public static Color DarkGrey => ConvertHtmlString("#A9A9A9");
        public static Color LightBlue => ConvertHtmlString("#ADD8E6");
        public static Color GreenYellow => ConvertHtmlString("#ADFF2F");
        public static Color PaleTurquoise => ConvertHtmlString("#AFEEEE");
        public static Color LightSteelBlue => ConvertHtmlString("#B0C4DE");
        public static Color PowderBlue => ConvertHtmlString("#B0E0E6");
        public static Color FireBrick => ConvertHtmlString("#B22222");
        public static Color DarkGoldenRod => ConvertHtmlString("#B8860B");
        public static Color MediumOrchid => ConvertHtmlString("#BA55D3");
        public static Color RosyBrown => ConvertHtmlString("#BC8F8F");
        public static Color DarkKhaki => ConvertHtmlString("#BDB76B");
        public static Color Silver => ConvertHtmlString("#C0C0C0");
        public static Color MediumVioletRed => ConvertHtmlString("#C71585");
        public static Color IndianRed => ConvertHtmlString("#CD5C5C");
        public static Color Peru => ConvertHtmlString("#CD853F");
        public static Color Chocolate => ConvertHtmlString("#D2691E");
        public static Color Tan => ConvertHtmlString("#D2B48C");
        public static Color LightGray => ConvertHtmlString("#D3D3D3");
        public static Color LightGrey => ConvertHtmlString("#D3D3D3");
        public static Color Thistle => ConvertHtmlString("#D8BFD8");
        public static Color Orchid => ConvertHtmlString("#DA70D6");
        public static Color GoldenRod => ConvertHtmlString("#DAA520");
        public static Color PaleVioletRed => ConvertHtmlString("#DB7093");
        public static Color Crimson => ConvertHtmlString("#DC143C");
        public static Color Gainsboro => ConvertHtmlString("#DCDCDC");
        public static Color Plum => ConvertHtmlString("#DDA0DD");
        public static Color BurlyWood => ConvertHtmlString("#DEB887");
        public static Color LightCyan => ConvertHtmlString("#E0FFFF");
        public static Color Lavender => ConvertHtmlString("#E6E6FA");
        public static Color DarkSalmon => ConvertHtmlString("#E9967A");
        public static Color Violet => ConvertHtmlString("#EE82EE");
        public static Color PaleGoldenRod => ConvertHtmlString("#EEE8AA");
        public static Color LightCoral => ConvertHtmlString("#F08080");
        public static Color Khaki => ConvertHtmlString("#F0E68C");
        public static Color AliceBlue => ConvertHtmlString("#F0F8FF");
        public static Color HoneyDew => ConvertHtmlString("#F0FFF0");
        public static Color Azure => ConvertHtmlString("#F0FFFF");
        public static Color SandyBrown => ConvertHtmlString("#F4A460");
        public static Color Wheat => ConvertHtmlString("#F5DEB3");
        public static Color Beige => ConvertHtmlString("#F5F5DC");
        public static Color WhiteSmoke => ConvertHtmlString("#F5F5F5");
        public static Color MintCream => ConvertHtmlString("#F5FFFA");
        public static Color GhostWhite => ConvertHtmlString("#F8F8FF");
        public static Color Salmon => ConvertHtmlString("#FA8072");
        public static Color AntiqueWhite => ConvertHtmlString("#FAEBD7");
        public static Color Linen => ConvertHtmlString("#FAF0E6");
        public static Color LightGoldenRodYellow => ConvertHtmlString("#FAFAD2");
        public static Color OldLace => ConvertHtmlString("#FDF5E6");
        public static Color Red => ConvertHtmlString("#FF0000");
        public static Color Fuchsia => ConvertHtmlString("#FF00FF");
        public static Color Magenta => ConvertHtmlString("#FF00FF");
        public static Color DeepPink => ConvertHtmlString("#FF1493");
        public static Color OrangeRed => ConvertHtmlString("#FF4500");
        public static Color Tomato => ConvertHtmlString("#FF6347");
        public static Color HotPink => ConvertHtmlString("#FF69B4");
        public static Color Coral => ConvertHtmlString("#FF7F50");
        public static Color DarkOrange => ConvertHtmlString("#FF8C00");
        public static Color LightSalmon => ConvertHtmlString("#FFA07A");
        public static Color Orange => ConvertHtmlString("#FFA500");
        public static Color LightPink => ConvertHtmlString("#FFB6C1");
        public static Color Pink => ConvertHtmlString("#FFC0CB");
        public static Color Gold => ConvertHtmlString("#FFD700");
        public static Color PeachPuff => ConvertHtmlString("#FFDAB9");
        public static Color NavajoWhite => ConvertHtmlString("#FFDEAD");
        public static Color Moccasin => ConvertHtmlString("#FFE4B5");
        public static Color Bisque => ConvertHtmlString("#FFE4C4");
        public static Color MistyRose => ConvertHtmlString("#FFE4E1");
        public static Color BlanchedAlmond => ConvertHtmlString("#FFEBCD");
        public static Color PapayaWhip => ConvertHtmlString("#FFEFD5");
        public static Color LavenderBlush => ConvertHtmlString("#FFF0F5");
        public static Color SeaShell => ConvertHtmlString("#FFF5EE");
        public static Color Cornsilk => ConvertHtmlString("#FFF8DC");
        public static Color LemonChiffon => ConvertHtmlString("#FFFACD");
        public static Color FloralWhite => ConvertHtmlString("#FFFAF0");
        public static Color Snow => ConvertHtmlString("#FFFAFA");
        public static Color Yellow => ConvertHtmlString("#FFFF00");
        public static Color LightYellow => ConvertHtmlString("#FFFFE0");
        public static Color Ivory => ConvertHtmlString("#FFFFF0");
        public static Color White => ConvertHtmlString("#FFFFFF");
    }
}